# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180816_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='already_eaten',
            field=models.NullBooleanField(verbose_name='Eaten'),
        ),
    ]
