# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_meal_already_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='already_eaten',
            field=models.NullBooleanField(editable=False, verbose_name='Eaten'),
        ),
    ]
