# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-28 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_merge'),
        ('nutrition', '0004_auto_20180822_1928'),
    ]

    operations = [
    ]
