# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author', verbose_name='Author'),
        ),
    ]
