# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180815_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_user',
            field=models.BooleanField(default=False, help_text='Check eligibility of this user to create users via the REST API', verbose_name='Field to verify whether a particular user can         add other users via the REST API'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rest_api_user',
            field=models.BooleanField(default=False, help_text='Boolean value to show whether this user was         created via the REST API or it is a wger user instance', verbose_name='Who created this user'),
        ),
    ]
