# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180816_2013'),
        ('core', '0010_auto_20180815_0053'),
    ]

    operations = [
    ]
