# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180814_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='drop_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='cycle_kind',
            field=models.CharField(choices=[('macrocycle', 'Macrocycle: One year'), ('mesocycle', 'Mesocycle: Two to six weeks'), ('microcycle', 'Microcycle: One week')], default='microcycle', max_length=10),
        ),
    ]
