# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180809_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession'),
        ),
    ]
