# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-09 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_workoutlog_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='session_id',
            new_name='session',
        ),
    ]
