# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20180822_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='drop_set',
        ),
        migrations.AddField(
            model_name='set',
            name='dropset',
            field=models.BooleanField(default=False, verbose_name='drop set'),
        ),
    ]
